# Read about configuration here: https://jekyllrb.com/docs/configuration/options/
title: 
description: 
keywords: 
url: 
permalink: pretty # Do not change this, it will break all links
timezone: America/New_York
markdown: kramdown
livereload: true
port: 4400

# Global variables
analytics_tag: 

# Navigation
enableNav: true
enableNavCollapse: true

# Notification
enableNotification: false
notificationMsgId: 1 # must increment when creating a new message
notificationMsg: Join the community!<br><a href=""></a>.
notificationExpiration: 3000000000 # epoch time in seconds

# Toast
enableToast: false
toastMsgId: 1 # must increment when creating a new message
toastTitle: Notice
toastMsg: # Best when under 100 characters
toastLink: # Optional, leave blank to omit
toastExpiration: 3000000000 # epoch time in seconds

# Assets
bootstrap_js: <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
bootstrap_css: <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">